
name: money_management_app
description: A simple money management application in Flutter.

publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.20.1
  sqflite: ^2.2.0
  path_provider: ^2.0.15
  fl_chart: ^0.69.2

flutter:
  uses-material-design: true
